title: Ivan Torrellas > Technology Leader

description: Technology Leader | 20+ Years Experience | AWS | GCP | Kubernetes | Senior DevOps & Cloud Architect

theme: jekyll-theme-minimal

markdown: kramdown

# Optional: Make it look more resume-like
show_downloads: false
