title: Ivan Torrellas > Platform Engineering & Cloud Architecture

description: Platform Engineering | Kubernetes Governance | AWS | GCP | DevSecOps | Tech Lead

theme: jekyll-theme-minimal

markdown: kramdown

# Optional: Make it look more resume-like
show_downloads: false
